"""cria tabela autores

Revision ID: 35b85d7e93dc
Revises: 
Create Date: 2026-09-02 09:57:24.988095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b85d7e93dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nacionalidade', sa.String(length=60), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autores_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autores_nome'))

    op.drop_table('autores')
    # ### end Alembic commands ###
